import express from 'express';
import { Router } from 'express';
import {register} from '../controllers/faculty/Controller.js';
import { createguest, get_guest_details} from '../controllers/guest/Controller.js';
import { createparticipate} from '../controllers/participate/Controller.js';
import {createevent,get_events_details ,getevent,updateevent, deleteevent, updatestatus} from '../controllers/event/Controller.js';
import { addvolunteer, getvolunteer ,creategroup, getvolunteer_group} from '../controllers/volunteer/Controller.js';
const router = Router();

router.route('/api/faculty/register').post(register);
router.route('/guest').post(createguest);
router.route('/api/event/participate').post(createparticipate);
router.route('/get_guest_details').get(get_guest_details);
router.route('/api/createevent').post(createevent);
router.route('/api/events').get(get_events_details);
router.route('/addvolunteer').post(addvolunteer);
router.route('/getvolunteer').get(getvolunteer);
router.route('/creategroup').post(creategroup);
router.route('/getvolunteer_group').get(getvolunteer_group);    
router.route('/api/getevent/:id').get(getevent);
router.route('/api/updateevent/:id').put(updateevent);
router.route('/api/deleteevent/:id').delete(deleteevent);
router.route('/api/event/updatestatus/:id/:status').patch(updatestatus).get(updatestatus);
export default router;