import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { FileText, Download, FolderOpen } from 'lucide-react'; // Added FolderOpen icon

const API = import.meta.env.VITE_API_URL;

export function Reports() {
    const [reports, setReports] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const res = await axios.get(`/api/reports`);
                console.log(res.data);
                
                // If the backend sends no data, make sure it defaults to an empty array
                setReports(res.data || []); 
                
            } catch (error) {
                console.error("Failed to fetch reports:", error);
                
                setReports([]); 
            } finally {
                setIsLoading(false);
            }
        };

        fetchReports();
    }, []);

    const formatDateTime = (ReportDate) =>{
        const date = new Date(ReportDate);
        return date.toLocaleString('en-IN',{
            day:'numeric',
            month:'2-digit',
            year:'2-digit',
            hour:'2-digit',
            minute:'2-digit',
            hour12:false
        })
    }
    const handleDownload = (reporturl) => {
        window.open(`${API}/${reporturl}`,"_blank");
    //      <a href="http://localhost:7000/reports/event-60.pdf" download="Event.pdf">
    // </a>
        // alert(`Triggering download for report ID: ${reportId}`);
    };

    if (isLoading) {
        return (
            <div className="p-8 bg-gray-50 min-h-screen flex items-center justify-center">
                <p className="text-gray-500 font-medium animate-pulse">Loading reports...</p>
            </div>
        );
    }

    return (
        <div className="p-8 bg-gray-50 min-h-screen">
            <h1 className="text-2xl font-bold text-gray-900 mb-6">Event Reports</h1>

            {/* --- CONDITIONAL RENDERING: Check if we have 0 reports --- */}
            {reports.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-24 bg-white border border-gray-200 rounded-xl shadow-sm">
                    <div className="bg-gray-50 p-4 rounded-full mb-4">
                        <FolderOpen size={48} className="text-gray-400" />
                    </div>
                    <h2 className="text-xl font-semibold text-gray-900">No Reports Available</h2>
                    <p className="text-gray-500 mt-2 max-w-md text-center">
                        There are currently no event reports generated. When faculty members complete their events, the data will appear here.
                    </p>
                </div>
            ) : (
                /* --- If we HAVE reports, map through them and draw the cards --- */
                <div className="flex flex-col gap-6">
                    {reports.map((report) => (
                        <div key={report.id} className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
                            
                            {/* Header Section */}
                            <div className="flex justify-between items-start mb-6">
                                <div className="flex gap-3">
                                    <div className="text-blue-600 mt-1">
                                        <FileText size={24} />
                                    </div>
                                    <div>
                                        <h2 className="text-lg font-semibold text-gray-900 leading-tight">
                                            {report.name}
                                        </h2>
                                        <p className="text-sm text-gray-500">
                                            Generated by {report.user_name}{`(${report.user_email})`}  on {formatDateTime(report.created_at)}
                                        </p>
                                    </div>
                                </div>
                                
                                <button 
                                    onClick={() => handleDownload(report.url)}
                                    className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors focus:ring-2 focus:ring-blue-500 focus:outline-none"
                                >
                                    <Download size={16} />
                                    Download
                                </button>
                            </div>

                            {/* Metrics Grid */}
                            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                                <div className="bg-blue-50/50 rounded-lg p-4 border border-blue-100/50">
                                    <p className="text-sm text-gray-600 mb-1">Participants</p>
                                    <p className="text-2xl font-bold text-blue-600">{report.participants || "-"}</p>
                                </div>
                                <div className="bg-orange-50/50 rounded-lg p-4 border border-orange-100/50">
                                    <p className="text-sm text-gray-600 mb-1">Budget Used</p>
                                    <p className="text-2xl font-bold text-orange-600">₹{report.actual_budget_used || 0}</p>
                                </div>
                            </div>

                            {/* Text Areas */}
                            <div className="space-y-4">
                                <div>
                                    <h3 className="text-sm font-semibold text-gray-700 mb-2">Outcomes</h3>
                                    <div className="bg-gray-50 rounded-lg p-3 text-sm text-gray-600 border border-gray-100 min-h-10">
                                        {report.outcome || "No outcomes provided."}
                                    </div>
                                </div>
                                
                            </div>

                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}